# Generated by Django 5.0.1 on 2024-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='er525', editable=False, max_length=12),
            preserve_default=False,
        ),
    ]
